Feat/services section
Demakk-Org/portfolio pull request #15
Opened 2024-09-14 11:58 UTC by ermias5

2024-09-14 22:20 UTC, Melka1 requested changes
I haven't finished it make the changes and get back to me fast.

2024-09-14 22:20 UTC, Melka1 commented on components/services/service-card.tsx
This is not a card, it is a list of card, bring the wrapping div here, and change the name of the component.

2024-09-14 22:20 UTC, Melka1 commented on components/footer-section/footer.tsx
check the default values of you use, for example, flex, default value flex-direction:row, line-14, check some other places to remove code that does not impact the DOM.
line 20, i don't get the point of wrapping the a in div just to put one component inside.

2024-09-14 22:20 UTC, Melka1 commented on components/contact-section/contact.tsx
line 35:  if the ' sign is creating a problem, just use entity code, &apos; for apostrophe, remove the curly braces, it becomes,  ">Let&apos;s Design Together<",  check out https://www.w3schools.com/html/html_entities.asp

2024-09-14 22:20 UTC, Melka1 commented on components/aboutMe/AboutMe.tsx
by default next-image is lazy loaded, please check the documentation

2024-09-19 08:10 UTC, closed without merging

2024-09-19 08:11 UTC, ermias5 commented
update branches and open new latest pr