Dev
Demakk-Org/portfolio pull request #19
Opened 2024-09-19 09:06 UTC by ermias5

2024-09-19 09:07 UTC, ermias5 commented
latest

2024-09-20 08:35 UTC, Melka1 requested changes

2024-09-20 08:35 UTC, Melka1 commented on tailwind.config.ts
there is a lot to unpack here,
-the name of a color can not be "bg-gray", when coloring a background it becomes,  bg-bg-gray, which is non-sense,
-consistency is key use all colors  in hex,
-name of font family can not be "nav-bar-text-21", change it,
-arrage the font sizes in ascending order and i dont get the naming process, why "mid", "lgi", "81xl", remove the inherit, us can use font-[inherit], avoid redundancy
-what the f*** is "8xs" for border radius
-the break points are redundant too, you already have "sm" for 640px, "lg" for 1024, "xl" for 1280, if you wanted smaller you could have used "xs", and i don't get the need for adding breakpoint higher than 1536px

2024-09-20 08:35 UTC, Melka1 commented on components/services/services.tsx
i dont get why you converted the p tag to flex if you wanted to center it why not use text-align:center

2024-09-20 08:35 UTC, Melka1 commented on components/services/service-card-list.tsx
remove empty className, why put the p in a div, if it does not have a style

2024-09-20 08:35 UTC, Melka1 commented on app/globals.css
remove comments before merging, that are not useful

2024-09-20 08:35 UTC, Melka1 commented on components/about-me/about.tsx
-empty classname
-line 26 {"About me"}, why?
-use the tags correctly line-29 text in div

2024-09-20 08:35 UTC, Melka1 commented on components/contact-section/contact.tsx
use div if it has more than one child or for styling puposes, line 37, h1 in div, why?

2024-09-21 21:22 UTC, Melka1 requested changes
reply fast

2024-09-21 21:22 UTC, Melka1 commented on components/navigation/navbar.tsx
line-34 don't repeat things use the conditional correctly, the default flex-direction is row no need  to specify it

2024-09-24 11:32 UTC, Melka1 requested changes

2024-09-24 11:32 UTC, Melka1 commented on components/navigation/navbar.tsx
what did you resolve? flex items-center justify-center desktop:gap-0?

2024-09-24 11:32 UTC, Melka1 commented on components/footer-section/footer.tsx
remove defau;t values from this file too

2024-09-24 11:56 UTC, Melka1 approved these changes

2024-09-24 11:59 UTC, Melka1 requested changes

2024-09-24 11:59 UTC, Melka1 commented on components/navigation/navbar.tsx
line 55 too, check every thing

2024-09-24 14:55 UTC, ermias5 commented on components/navigation/navbar.tsx
done!

2024-09-24 15:22 UTC, Melka1 approved these changes

2024-09-24 15:22 UTC, merged