Dashboard
Demakk-Org/portfolio pull request #36
Opened 2024-11-15 14:22 UTC by ermias5

2024-11-15 18:34 UTC, Melka1 requested changes

2024-11-15 18:34 UTC, Melka1 commented on components/services/service-section.tsx
wtf?

2024-11-15 18:34 UTC, Melka1 commented on components/lib/firebase-crud/create-data.ts
correct everything! why did you include the data in the commit?

2024-11-15 18:34 UTC, Melka1 commented on components/hero/Hero.tsx
Is it hard to include Error and loading?

2024-11-16 13:54 UTC, Melka1 requested changes

2024-11-16 13:54 UTC, Melka1 commented on components/projects/project-card.tsx
What about adding a placeholder image if there is no image

2024-11-16 13:54 UTC, Melka1 commented on components/lib/firebase-crud/create-data.ts
read the last comment?

2024-11-16 18:57 UTC, Melka1 requested changes

2024-11-16 18:57 UTC, Melka1 commented on components/hero/Hero.tsx
line-33 remove the braces

2024-11-16 18:57 UTC, Melka1 commented on components/lib/firebase-crud/post-data.ts
Amnesia alebh ende!!!!!!!!

2024-11-16 18:57 UTC, Melka1 commented on components/projects/project-card.tsx
Remove the state, you don't need it

2024-11-19 13:15 UTC, Melka1 requested changes

2024-11-19 13:15 UTC, Melka1 commented on app/dashboard/form-handler.tsx
try to move the api request out of this file, just invoke it here, read about clean architecture.
and even if the createFireStoreData fails, it show the Alert that it was successful

2024-11-20 23:39 UTC, Melka1 requested changes

2024-11-20 23:39 UTC, Melka1 commented on app/dashboard/form-handler.tsx
convert this to a custom hook and return {formData, handleInputChange, handleFileChange, handleSubmit} and use it on the form-component, when you use the word "handle" make sure it is not a function that return a component.

2024-11-20 23:39 UTC, Melka1 commented on components/theme-toggle/theme.tsx
the name is problematic, theme should be enum not string "light" or "dark"... (think please!!)

2024-11-21 20:51 UTC, Melka1 requested changes

2024-11-21 20:51 UTC, Melka1 commented on hooks/useFormHandler.ts
handle submit api won't throw error so the try catch is useless

2024-11-21 20:51 UTC, Melka1 commented on components/lib/firebase-crud/create-data.ts
work on your error handling

2024-11-21 20:51 UTC, Melka1 commented on app/dashboard/form-service.ts
line-40 this function doesn't throw error, therefore there isn't any to catch

2024-11-22 11:52 UTC, Melka1 requested changes

2024-11-22 11:52 UTC, Melka1 commented on app/dashboard/form-service.ts
nothing has changed

2024-11-22 11:52 UTC, Melka1 commented on components/lib/firebase-crud/create-data.ts
nothing has changed

2024-11-22 11:52 UTC, Melka1 commented on hooks/useFormHandler.ts
Correct your error handling, this tells that it is always successful.

2024-11-30 11:15 UTC, Melka1 requested changes

2024-11-30 11:15 UTC, Melka1 commented on components/projects/project-section.tsx
what is the use of changing the skills to lowercase?

2024-11-30 20:30 UTC, ermias5 commented on components/projects/project-section.tsx
to filter out projects with out case sensitive when data uploading

2024-12-02 11:40 UTC, Melka1 requested changes

2024-12-02 11:40 UTC, Melka1 commented on app/page.tsx
Cant you use the footer style inside the the footer component

2024-12-02 11:40 UTC, Melka1 commented on components/testimonials/testimonial-section.tsx
remove line 37

2024-12-05 05:51 UTC, Melka1 approved these changes

2024-12-05 05:52 UTC, Melka1 approved these changes

2024-12-05 05:52 UTC, merged