Feat/dashboard crud
Demakk-Org/portfolio pull request #39
Opened 2024-12-26 12:22 UTC by ermias5

2024-12-28 13:37 UTC, Melka1 requested changes

2024-12-28 13:37 UTC, Melka1 commented on components/dashboard/add-data.tsx
The name looks like it is a function not component. Change it.

2024-12-28 13:37 UTC, Melka1 commented on components/dashboard/add-data.tsx
This code is great!

2024-12-28 13:37 UTC, Melka1 commented on components/dashboard/authForm.tsx
use custom hook to separate the logic with the component, return all the necessary information from the custom hook.

2024-12-28 13:37 UTC, Melka1 commented on components/dashboard/authForm.tsx
> +          required
The required is not good enough, it can be bypassed easily, use your own validation function.

2024-12-28 13:37 UTC, Melka1 commented on components/dashboard/dashboard-crud.ts
It would have been better if u used class instead of object.

2024-12-28 13:37 UTC, Melka1 commented on components/dashboard/edit-delete-data.tsx
The name has issues. Correct it.

2024-12-28 13:37 UTC, Melka1 commented on components/dashboard/form-field.ts
Find a better name, add 'config' at the end.

2024-12-28 13:37 UTC, Melka1 commented on components/dashboard/form.tsx
> +  formData: { [key: string]: any };
Avoid using any at any cost.

2024-12-28 13:37 UTC, Melka1 commented on components/dashboard/form.tsx
> +  fields: { name: string; label: string; type: string; rows?: number }[];
Create a type for field. Use appropriate name.

2024-12-28 13:37 UTC, Melka1 commented on components/dashboard/form.tsx
> +              className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-500 focus:ring-opacity-50"
use a common style and combine using twMerge or string manipulation

2024-12-28 13:37 UTC, Melka1 commented on components/dashboard/modal.tsx
Is there a modal without a title. If not make it required.

2024-12-28 13:37 UTC, Melka1 commented on components/dashboard/service-item.tsx
> +  category: string;
Make the category enum

2024-12-28 13:37 UTC, Melka1 commented on components/dashboard/service-item.tsx
> +          {row.skills ? row.skills.join(", ") : ""}
If skills is conditional, it should be row?.skills, if the type of skills is array, row.skills.length is better

2024-12-28 13:37 UTC, Melka1 commented on components/dashboard/update-dashboard-data.tsx
> +// import AddNewData from "./add-data";
Remove this line

2024-12-28 13:37 UTC, Melka1 commented on components/hero/Hero.tsx
> +              <button
Just use link with the ID as its href instead of the button

2024-12-28 13:37 UTC, Melka1 commented on components/lib/firebase-crud/create-data.ts
> +      alert(`Document created to ${category} categoty`);
Use snack bar instead of alert.

2024-12-28 13:37 UTC, Melka1 commented on components/lib/firebase-crud/update-data.ts
> +const updateFirestoreData = async ({ category, docId, data }: any) => {
Avoid using 'any' as type

2025-01-08 05:39 UTC, Melka1 requested changes

2025-01-08 05:39 UTC, Melka1 commented on app/dashboard/layout.tsx
> +      setLoading(true);
I don't think the setLoading on line 15 and 28 are doing anything

2025-01-08 05:39 UTC, Melka1 commented on app/dashboard/projects/page.tsx
> +    <>
I don't get the purpose of the fragment here

2025-01-08 05:39 UTC, Melka1 commented on app/dashboard/projects/page.tsx
> +  if (isLoading) return <div className="p-[300px]">Loading...</div>;
why not return a p tag instead of div

2025-01-08 05:39 UTC, Melka1 commented on app/dashboard/services/page.tsx
> +    <>
same read the previous comments

2025-01-08 05:39 UTC, Melka1 commented on app/dashboard/testimonials/page.tsx
> +    <>
and again!

2025-01-08 05:39 UTC, Melka1 commented on app/dashboard/upload-cv/page.tsx
> +    <>
and again!

2025-01-08 05:39 UTC, Melka1 commented on components/about-me/about.tsx
> +        className={`flex items-center justify-center px-[5%]  pt-[10%]  gap-5 font- dark:text-white  tablet:gap-[140px] tablet:px-[40%] desktop:px-[30%]`}
what is the font "font- "

2025-01-08 05:39 UTC, Melka1 commented on components/dashboard/dashboard-crud/delete-data.tsx
> +          handleDeleteClick(row.id);
this function name is weird, change it

2025-01-08 05:39 UTC, Melka1 commented on components/dashboard/dashboard-crud/delete-data.tsx
> +          handleDeleteClick(row.id);
ask chatgpt for better names

2025-01-08 05:39 UTC, Melka1 commented on components/dashboard/dashboard-crud/edit-data.tsx
> +              setIsEditing(false);
why are setIsEditing(false) and cancelEditing different

2025-01-08 05:39 UTC, Melka1 commented on components/dashboard/modal.tsx
> +        onClick={(e) => e.stopPropagation()}
why do you need the stop propagation method on this div

2025-01-08 05:39 UTC, Melka1 commented on components/hero/Hero.tsx
> +      <div className="fixed flex items-center justify-center top-[10rem] left-[1rem] cursor-pointer tablet:top-[10rem] tablet:left-[2rem] laptop:top-[20rem] laptop:left-[7rem]">
read the tailwind documentation, don't just write codes. left-4 is left-[1rem] the square bracket is for the purpose of custom sizes, not for everything. FOLLOW DOCUMENTATION that is what makes you a better programmer

2025-01-08 05:39 UTC, Melka1 commented on hooks/useFormHandler.ts
> +      deleteItem(itemToDelete);
What if it fails to delete? it still applies the next two functions, correct it

2025-01-08 11:55 UTC, ermias5 commented on components/dashboard/modal.tsx
> +        onClick={(e) => e.stopPropagation()}
because to prevent closing event handler inside buttons and onchange events

2025-01-09 14:38 UTC, Melka1 requested changes

2025-01-09 14:38 UTC, Melka1 commented on components/dashboard/dashboard-crud/delete-data.tsx
> +          handleDeleteClick(row.id);
Change the name before marking it resolved

2025-01-09 14:38 UTC, Melka1 commented on components/dashboard/modal.tsx
> +        onClick={(e) => e.stopPropagation()}
This is just a div though.

2025-01-09 14:38 UTC, Melka1 commented on components/hero/Hero.tsx
> +      <div className="fixed flex items-center justify-center top-[10rem] left-[1rem] cursor-pointer tablet:top-[10rem] tablet:left-[2rem] laptop:top-[20rem] laptop:left-[7rem]">
Fix it first, and don't mark anything resolved. I am responsible for that.

2025-01-09 14:38 UTC, Melka1 commented on hooks/useFormHandler.ts
> +      deleteItem(itemToDelete);
Where are the changes to resolve this.

2025-01-09 17:47 UTC, ermias5 commented on components/dashboard/dashboard-crud/delete-data.tsx
> +          handleDeleteClick(row.id);
RemoveDashboardItemData

2025-01-09 17:52 UTC, ermias5 commented on components/dashboard/modal.tsx
> +        onClick={(e) => e.stopPropagation()}
if i don't implement this method at event object i can't edit data and onclose event handler is excuted

2025-01-09 18:29 UTC, ermias5 commented on hooks/useFormHandler.ts
> +      deleteItem(itemToDelete);
function confirmDelete() {
  async function confirmDelete() {
    if (itemToDelete) {
      deleteItem(itemToDelete);
      try {
        await deleteItem(itemToDelete);
        setIsConfirmingDelete(false);
        setItemToDelete(null);
      } catch (e) {
        console.error("Error deleting item", e);
      }
    }
    setIsConfirmingDelete(false);
    setItemToDelete(null);
  }

2025-01-13 16:15 UTC, Melka1 requested changes

2025-01-13 16:15 UTC, Melka1 commented on components/dashboard/dashboard-crud/create-dashboard-data.tsx
> +  const [isAdding, setIsAdding] = useState<boolean>(false);
[isFormModalOpen, setIsFormmodalOpen] use this instead

2025-01-13 16:15 UTC, Melka1 commented on components/dashboard/dashboard-crud/edit-data.tsx
> +              setIsEditing(false);
Respond

2025-01-13 16:15 UTC, Melka1 commented on components/dashboard/dashboard-crud/remove-dashboard-item-data.tsx
> +export default function RemoveDashboardItemData<T extends DataItem>({
Correct the name of the component.

2025-01-13 16:15 UTC, Melka1 commented on components/dashboard/dashboard-crud/remove-dashboard-item-data.tsx
> +          handleDeleteClick(row);
i don't like this name too

2025-01-13 16:15 UTC, Melka1 commented on components/dashboard/dashboard-crud/update-dashboard-data.tsx
> +export default function UpdateDashboardData<T extends DataItem>({
You current task should be updating the name all functions and components. (Carefully!)

2025-01-13 16:15 UTC, Melka1 commented on components/dashboard/data-input-form.tsx
> +    <>
no need to use fragment.

2025-01-13 16:15 UTC, Melka1 commented on components/dashboard/updated-form.ts
> +    typeof formData.skills === "string"
why is there two types here for the formData.skills (sstring and array)

2025-01-13 16:15 UTC, Melka1 commented on hooks/useFormHandler.ts
> +      await dashboardCRUD.deleteItem(category, id ?? "", fileUrl);
if id is undefined of null you have to return not path "" as id

2025-01-15 08:21 UTC, ermias5 commented on components/dashboard/dashboard-crud/edit-data.tsx
> +              setIsEditing(false);
setIsEdititng(false) is for modal open and closing state
where as cancelEditig for clearig form entries

2025-01-15 12:52 UTC, ermias5 commented on components/dashboard/updated-form.ts
> +    typeof formData.skills === "string"
if skills don't update during editing it set as string and change to array

2025-01-16 06:44 UTC, Melka1 requested changes

2025-01-16 06:44 UTC, Melka1 commented on components/contact-section/contact.tsx
> +      .send(serviceId ?? "", templateId ?? "", templateParams, publicKey)
Will it work with serviceId as "", or templateId as "", if not, why not show an error before making the request, and you dont need the null check, fix it!

2025-01-16 06:44 UTC, Melka1 commented on components/contact-section/contact.tsx
> +  const [success, setSuccess] = useState("");
This state is not useful, use a boolean instead, USE CORRECT NAMING

2025-01-16 06:44 UTC, Melka1 commented on components/contact-section/contact.tsx
> +      to_name: "Ermias Alhegn",
Why are hard coding a name here

2025-01-16 06:44 UTC, Melka1 commented on components/contact-section/contact.tsx
> +    emailjs
Contain the request in a try-catch block

2025-01-16 06:44 UTC, Melka1 commented on components/contact-section/contact.tsx
> +      );
or a catch block here, if it has.

2025-01-16 06:44 UTC, Melka1 commented on components/dashboard/dashboard-crud/edit-dashboard-items.tsx
> +import RemoveDashboardItemData from "./remove-dashboard-item";
import RemoveDashboardItemData from "./remove-dashboard-item"; i have this import and trying to apply clean code, what kind of file does it seem like by reading the name of the file,
Give the above prompt to chatgpt and read the response, the name is far from correct.

2025-01-16 06:44 UTC, Melka1 commented on components/dashboard/dashboard-crud/remove-dashboard-item.tsx
the name is not there yet

2025-01-16 06:44 UTC, Melka1 commented on components/dashboard/dashboard-crud/update-dashboard-data.tsx
> +import EditDashboardData from "./edit-dashboard-items";
i don't see any difference, ask chatgpt for better name

2025-01-16 06:44 UTC, Melka1 commented on components/hero/social-links.tsx
Make the list of social links from the database, this is a request from Ephrem. Effective immediately.

2025-01-16 06:44 UTC, Melka1 commented on hooks/useFormHandler.ts
> +  // async function confirmDelete() {
why is this here.? if you are planning to use it in the future, the name is incorrect

2025-01-16 06:44 UTC, Melka1 commented on hooks/useFormHandler.ts
>    async function confirmDelete() {
why?

2025-01-16 07:10 UTC, Melka1 requested changes

2025-01-16 07:10 UTC, Melka1 commented on app/dashboard/layout.tsx
> +  const [isAuthorized, setIsAuthorized] = useState<boolean>(false);
if you give a value of false, by default it is boolean.

2025-01-16 07:10 UTC, Melka1 commented on components/dashboard/dashboard-crud/dashboard-item-deletion.tsx
> +export default function RemoveDashboardItem<T extends DataItem>({
try another

2025-01-16 07:10 UTC, Melka1 commented on components/dashboard/dashboard-crud/dashboard-item-deletion.tsx
> +    onDeleteItemInitiate,
good, but could be better, it would suffice for now.

2025-01-16 12:51 UTC, ermias5 commented on components/contact-section/contact.tsx
> +      to_name: "Ermias Alhegn",
just for template response it's ok to be not included

2025-01-17 13:51 UTC, Melka1 requested changes

2025-01-17 13:51 UTC, Melka1 commented on app/dashboard/layout.tsx
> +  const [isAuthorized, setIsAuthorized] = useState<boolean>();
just make the initial value false, and remove the type

2025-01-17 13:51 UTC, Melka1 commented on components/dashboard/row-data-displayer.tsx
> +      {/* {category === "testimonials" && ( */}
why dont you remove the comments on the pr?

2025-01-17 13:51 UTC, Melka1 commented on components/footer-section/footer.tsx
> +// import SocialLinks from "../hero/social-links";
wtf?

2025-01-17 13:51 UTC, Melka1 commented on components/lib/firebase-crud/delete-resource-handler.ts
> +export default deleteResourceFromFirestoreAndStorage;
the previous name was actually better

2025-01-17 13:51 UTC, Melka1 commented on components/navigation/side-navigation.tsx
> +// import SocialLinks from "../hero/social-links";
i will always send it back!!!!!

2025-01-17 13:51 UTC, Melka1 commented on hooks/useContactFormHandler.ts
> +  const [formSuccess, setFormSuccess] = useState(false);
boolean mostly starts with, has or is,

2025-01-17 18:28 UTC, ermias5 commented on components/dashboard/row-data-displayer.tsx
> +      {/* {category === "testimonials" && ( */}
coz there are other changes in that file

2025-01-17 18:30 UTC, ermias5 commented on components/footer-section/footer.tsx
> +// import SocialLinks from "../hero/social-links";
what? there was just some change in this file and removed commented line of code

2025-01-17 18:30 UTC, ermias5 commented on components/lib/firebase-crud/delete-resource-handler.ts
> +export default deleteResourceFromFirestoreAndStorage;
ok

2025-01-17 18:31 UTC, ermias5 commented on components/navigation/side-navigation.tsx
> +// import SocialLinks from "../hero/social-links";
for what purpose

2025-01-17 20:20 UTC, Melka1 approved these changes

2025-01-18 09:02 UTC, merged